[profile.default]
src = "src"
out = "out"
evm_version = "shanghai"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
fs_permissions = [{ access = "read-write", path = "./deployments" }]

[rpc_endpoints]
ritual = "https://rpc.ritualfoundation.org"
